# Generated by Django 5.2.2 on 2025-06-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0004_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('online', 'Онлайн-оплата')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='pending', max_length=255),
        ),
    ]
